image: nixos/nix

before_script:
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
  - nix-channel --update

pages:
  script: nix-shell --run make
  artifacts:
    paths:
    - public
